### ISSUE TITLE
deactivate not working when used inside NotificationStack

### ISSUE THREAD

**Issue by elisherer** [pburtchaell/react-notification#109]
## Version Number
6.6.0
## Test Case
Deactivate not working when used in notifications under a NotificationStack.
## Steps to Reproduce
Create a NotificationStack and provide a notification which has an onClick function which uses the deactivate parameter.
## Expected Behavior
The deactivate call will be successful.
## Actual Behavior
Exception thrown:
```
Uncaught TypeError: deactivate is not a function
    at _extends.onClick (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:93187:16)
    at StackedNotification.handleClick (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:93698:28)
    at Notification.handleClick (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:93428:28)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:16356:17)
    at executeDispatch (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:16141:22)
    at Object.executeDispatchesInOrder (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:16164:6)
    at executeDispatchesAndRelease (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:15558:23)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:15569:11)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:16453:10)
    at Object.processEventQueue (http://localhost:8080/script/main.js?v=b42af8c45fd9393c748e:15772:8)
```

**Comment by elisherer** [comment]
This works on the previous version 6.5.2. Guessing it's because of the new global onClick change (not considering the deactivate function argument)

**Comment by pburtchaell** [comment]
> Guessing it's because of the new global onClick change

The docs don't mention this, but in this case, the `deactivate` argument is the second argument. Here is a test case for this:

```js
it('should fire onClick with argument `deactivate`', (done) => {
    const wrapper = mount(
      <NotificationStack
        notifications={[{
          ...mockNotification,
          onClick: (notification, deactivate) => {
            console.log(typeof deactivate); // => 'function'
            done();
          }
        }]}
        onDismiss={() => null}
      />
    );

    const notification = wrapper.find('.notification-bar-action');
    notification.simulate('click');
  });
```

I think this API is a bit confusing though, and I'd like to start working on a version 7 release with a more API. 

Let me know if this resolves your issue! Sorry for the confusion.
